service: slack-standup-sls

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    SLACK_BOT_TOKEN: ${file(./.env.yml):SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${file(./.env.yml):SLACK_SIGNING_SECRET}
    CHANNEL_NAME: ${file(./.env.yml):CHANNEL_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'

functions:
  start:
    handler: src/start.handler
    events:
      - schedule:
          name: daily-start-standup
          rate: cron(0 7 ? * MON-FRI *)
  reminder:
    handler: src/reminder.handler
    events:
      - schedule:
          name: daily-reminder-standup
          rate: cron(45 8 ? * MON-FRI *)
  overview:
    handler: src/overview.handler
    events:
      - schedule:
          name: daily-deadline-standup
          rate: cron(0 9 ? * MON-FRI *)
  interactive:
    handler: src/interactive.handler
    events:
      - http:
          path: interactive
          method: post
  events:
    handler: src/events.handler
    events:
      - http:
          path: events
          method: post

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: standupDate
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: standupDate
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-offline
